CREATE TABLE books (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    published_at TIMESTAMP NOT NULL,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    pages INT NOT NULL,
    language VARCHAR(50) NOT NULL,
    publisher VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
